---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: collect-snapshot-spec
  labels:
    app.kubernetes.io/version: "4.5.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: >-
    Tekton task to collect .spec data from the Snapshot
  params:
    - name: snapshot
      type: string
      description: The namespaced name of the Snapshot
    - name: subdirectory
      description: Subdirectory inside the workspace to be used
      type: string
      default: ""
  workspaces:
    - name: data
      description: Workspace to save the CR jsons to
  results:
    - name: snapshotSpec
      type: string
      description: The relative path in the workspace to the stored snapshotSpec json
  steps:
    - name: collect-snapshot-spec
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      env:
        - name: "SNAPSHOT"
          value: '$(params.snapshot)'
      script: |
        #!/usr/bin/env sh
        set -eo pipefail

        if [ -n "$(params.subdirectory)" ]; then
          mkdir -p $(workspaces.data.path)/$(params.subdirectory)
        fi

        echo -e "\nFetching Snapshot Spec"
        SNAPSHOTSPEC_PATH=$(params.subdirectory)/snapshot_spec.json
        echo -n $SNAPSHOTSPEC_PATH > $(results.snapshotSpec.path)
        get-resource "snapshot" "${SNAPSHOT}" "{.spec}" | tee $(workspaces.data.path)/$SNAPSHOTSPEC_PATH
